### PR TITLE
Add better documentation to README

### PR DESCRIPTION
**Pull request by hollingberry**
Hi @toy! I stumbled upon this gem — truly a gem — a few weeks ago while searching for a simple Ruby concurrency library. For some reason, the other gems I tried didn't work at all (I was SAX parsing a bunch of giant XML files?), but this did. Anyway, I cleaned up the documentation so hopefully more people discover this. I'm amazed that there's only 6 stars on the project.

Thanks for creating this and happy new year!

### CODE REVIEW

**Comment by toy** [comment]
Thanks, I am glad that you've found it useful! And it seems your post got some attention to this gem.

More examples in readme is great! Few notes:
What is your reason to change file extension and header?
Example with primes may be misleading as it will just find primes multiple times. It will be faster in jruby with `in_threads` by using system threads, but in MRI it will be a bit slower due to overhead of switching threads.

Happy new year to you too!

**Comment by hollingberry** [comment]
I put the header back how it was, I decided that it looks cleaner this way (and the raw markdown is WAY easier to read). I also got rid of the example with primes.

I think renaming README.markdown to README.md is fine, it's more common but I'm happy to change it back if you care one way or another.

**Comment by hollingberry** [comment]
@toy Do you still want this?

**Comment by toy** [comment]
@hollingberry Yes.

**Comment by toy** [comment]
[Merged](ce241c679a78d5a2041da468fdd776d154ba2fed), thanks!

**Pull request closed without merging**
